import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  //await knex('white_cards').del();
  //await knex('black_cards').del();
  //await knex('card_sets').del();

  const [setId] = await knex('card_sets').insert({
    name: 'Liberecká banda 2026',
    description: 'Upravená sada pro jednu libereckou bandu.',
    is_public: true,
    slug: 'liberecka-banda-2026',
  });

  await knex('black_cards').insert([
    { card_set_id: setId, text: 'Ahoj Lide.cz! Jsem ____. Zeptejte se mne na cokoli.', pick: 1 },
    { card_set_id: setId, text: 'Poznejte X-treme Baseball! Je to jako baseball, ale s ____.', pick: 1 },
    { card_set_id: setId, text: 'Co je Batmanova tajná úchylka?', pick: 1 },
    { card_set_id: setId, text: 'Nová bezpečnostní pravidla zakazují v letadlech ____.', pick: 1 },
    { card_set_id: setId, text: 'Další kniha od J. K. Rowlingové: Harry Potter a komnata ____.', pick: 1 },
    { card_set_id: setId, text: 'Je to tak, zabil jsem ____. Ptáte se jak? ____.', pick: 2 },
    { card_set_id: setId, text: 'Pane profesore, omlouvám se, ale domácí úkol jsem nemohl dokončit kvůli ____.', pick: 1 },
    { card_set_id: setId, text: 'Oskara za ____ získává ____.', pick: 2 },
    { card_set_id: setId, text: 'Kámo, nechoď na ten záchod. Je tam ____.', pick: 1 },
    { card_set_id: setId, text: 'Jak jsem přišel o panictví?', pick: 1 },
    { card_set_id: setId, text: 'Je smutné, že se dnes děti zaplétají s ____.', pick: 1 },
    { card_set_id: setId, text: 'Krok 1: ____. Krok 2: ____. Krok 3: zisk.', pick: 2 },
    { card_set_id: setId, text: 'Vsad\' se, že si nedáš ____ jenom jednou.', pick: 1 },
    { card_set_id: setId, text: 'Ale mládeži, já nepotřebuji drogy, abych se sjel. Frčím na ____.', pick: 1 },
    { card_set_id: setId, text: 'A jako své další číslo (si) vytáhnu z ____ ____.', pick: 2 },
    { card_set_id: setId, text: 'Co je moje tajná superschopnost?', pick: 1 },
    { card_set_id: setId, text: 'Tento týden mám očistu. Nic než kapustový džus a ____.', pick: 1 },
    { card_set_id: setId, text: '____ + ____ = ____.', pick: 3 },
    { card_set_id: setId, text: 'Aspoň jednou bych od Tebe rád slyšel: "Díky mámo. Díky za ____."', pick: 1 },
    { card_set_id: setId, text: 'Tati, proč maminka pláče?', pick: 1 },
    { card_set_id: setId, text: 'Když jsem byl na tripu, ____ se změnilo v ____.', pick: 2 },
    { card_set_id: setId, text: '50 % všech manželství končí s/v ____.', pick: 1 },
    { card_set_id: setId, text: 'Drazí Američané, do 10 let dostaneme ____ na Měsíc.', pick: 1 },
    { card_set_id: setId, text: 'Místo uhlí teď Mikuláš dětem dává ____.', pick: 1 },
    { card_set_id: setId, text: 'Život amerických Indiánů se navždy změnil, když jim Bílý muž přinesl ____.', pick: 1 },
    { card_set_id: setId, text: 'Čím Česká Asociace Učitelů inspiruje městské studenty ke studiu?', pick: 1 },
    { card_set_id: setId, text: 'Možná se tak narodila, možná je to ____.', pick: 1 },
    { card_set_id: setId, text: 'Na co zrovna teď myslí prezident Pavel?', pick: 1 },
    { card_set_id: setId, text: 'Běloši mají rádi ____.', pick: 1 },
    { card_set_id: setId, text: '____ je šikmá plocha, vedoucí k ____.', pick: 2 },
    { card_set_id: setId, text: 'Proč mě bolí celé tělo?', pick: 1 },
    { card_set_id: setId, text: 'Romantická večeře při svíčkách by nebyla úplná bez ____.', pick: 1 },
    { card_set_id: setId, text: 'Zrovna jsem viděl toto skandální video. Prosím retweetujte! #stop____.', pick: 1 },
    { card_set_id: setId, text: 'Zábavný tip! Když Vás partner požádá o orální sex, zkuste ho místo toho překvapit s ____.', pick: 1 },
    { card_set_id: setId, text: 'Náš třídní výlet úplně pokazilo ____.', pick: 1 },
    { card_set_id: setId, text: 'Co je nejlepší přítel ženy?', pick: 1 },
    { card_set_id: setId, text: 'Milé Bravíčko, mám potíže s ____ a potřebuji poradit.', pick: 1 },
    { card_set_id: setId, text: 'V novém dílu "Skandálních odhalení" mladá rodina zjistí, že ____ byl celou dobu ____.', pick: 2 },
    { card_set_id: setId, text: 'Kdybych byl předsedou vlády, ustanovil bych ministerstvo ____.', pick: 1 },
    { card_set_id: setId, text: 'Co přede mnou rodiče tají?', pick: 1 },
    { card_set_id: setId, text: 'Co pokaždé oživí párty?', pick: 1 },
    { card_set_id: setId, text: 'POKUD máš rád ____, TAK jsi buran!', pick: 1 },
    { card_set_id: setId, text: 'Proč byl můj první polibek tak rozpačitý?', pick: 1 },
    { card_set_id: setId, text: 'Mám 99 problémů, ale ____ mezi nimi není.', pick: 1 },
    { card_set_id: setId, text: '____ Je to past!', pick: 1 },
    { card_set_id: setId, text: 'V nové reality show TV Nova spolu bydlí osm sexy nezadaných a ____.', pick: 1 },
    { card_set_id: setId, text: 'Co by babičku rozrušilo, ale zároveň zvláštním způsobem okouzlilo?', pick: 1 },
    { card_set_id: setId, text: '____, myslela, že je to známka punku', pick: 1 },
    { card_set_id: setId, text: 'Nikdy jsem úplně nechápal ____, dokud jsem se nesetkal s ____.', pick: 2 },
    { card_set_id: setId, text: 'Při sexu rád myslím na ____.', pick: 1 },
    { card_set_id: setId, text: 'Co ukončilo můj poslední vztah?', pick: 1 },
    { card_set_id: setId, text: 'Co je to za zvuk?', pick: 1 },
    { card_set_id: setId, text: 'Hmm, chlapi. Ja vím, že to byl můj nápad, ale mám vážné pochybnosti o ____.', pick: 1 },
    { card_set_id: setId, text: 'Proč se tak lepím?', pick: 1 },
    { card_set_id: setId, text: 'Nejsem žádný doktor, ale jsem si docela jist, že trpíš ____.', pick: 1 },
    { card_set_id: setId, text: 'Čeho je tuna na nebesích?', pick: 1 },
    { card_set_id: setId, text: 'Co ti pokaždé umožní si vrznout?', pick: 1 },
    { card_set_id: setId, text: 'Říkali, že jsme šílení. Říkali, že nejde nacpat ____ do ____. Pletli se.', pick: 2 },
    { card_set_id: setId, text: 'Prima Love uvádí: "____: příběh ____."', pick: 2 },
    { card_set_id: setId, text: '____: testováno dětmi, schváleno matkami.', pick: 1 },
    { card_set_id: setId, text: 'Proč nemůžu v noci spát?', pick: 1 },
    { card_set_id: setId, text: 'Co to tu tak smrdí?', pick: 1 },
    { card_set_id: setId, text: 'Proč se Daniela tak zpotila?', pick: 1 },
    { card_set_id: setId, text: 'Znám křišťálovou studánku, kde nejhlubší je les, tam roste tmavé kapradí a vůkol ____.', pick: 1 },
    { card_set_id: setId, text: 'Tuto sezónu na Broadwayi uvádí muzikál: ____.', pick: 1 },
    { card_set_id: setId, text: 'Paci, paci, pacičky, táta koupil botičky. A maminka pásek, za ____.', pick: 1 },
    { card_set_id: setId, text: 'Než vás zabiju, pane Bonde, musím vám ukázat ____.', pick: 1 },
    { card_set_id: setId, text: 'Nedávná klinická studie ukazuje, že studenti VŠ mají o 50% méně sexu, pokud jsou vystaveni ____.', pick: 1 },
    { card_set_id: setId, text: 'Seznamte ses dvojicí superhrdiny a pomocníka! Je to ____ a ____.', pick: 2 },
    { card_set_id: setId, text: 'Dále na ČT Sport: Světový šampionát v ____.', pick: 1 },
    { card_set_id: setId, text: 'Kdybych byl miliardář, postavil bych 50m sochu na počest ____.', pick: 1 },
    { card_set_id: setId, text: 'Vojenští historikové dodnes oceňují Alexandra Velikého za použití ____ proti Peršanům.', pick: 1 },
    { card_set_id: setId, text: 'Válka! K čemu je dobrá?', pick: 1 },
    { card_set_id: setId, text: 'Co mi způsobuje neovladatelnou plynatost?', pick: 1 },
    { card_set_id: setId, text: 'Nová Škoda Kodiaq. Se silou a prostorem na ____ kamkoli chcete.', pick: 1 },
    { card_set_id: setId, text: 'Omluvte mě pánové, mám schůzku s ____.', pick: 1 },
    { card_set_id: setId, text: 'Alternativní medicína nyní využívá léčivé síly ____.', pick: 1 },
    { card_set_id: setId, text: 'Jako matka pěti rozdivočelých hochů jsem zvyklá na ____.', pick: 1 },
    { card_set_id: setId, text: 'Dobrá práce, brácho. ____', pick: 1 },
    { card_set_id: setId, text: 'Dnes v Sama doma: "Pomoc! Můj syn má ____."', pick: 1 },
    { card_set_id: setId, text: 'Poradím si, s trochou pomoci od ____.', pick: 1 },
    { card_set_id: setId, text: 'NEchoďte sem! Našel jsem ____ v mých špagetách carbonara!', pick: 1 },
    { card_set_id: setId, text: 'Piju abych zapomněl na ____.', pick: 1 },
    { card_set_id: setId, text: 'Jsem Tomáš Rosický. Když zrovna nestřílím góly, tak mě najdete u ____.', pick: 1 },
    { card_set_id: setId, text: 'Za co stojí žít?', pick: 1 },
    { card_set_id: setId, text: 'Bageterie Boulevard: dnes máme ____.', pick: 1 },
    { card_set_id: setId, text: 'Pane a paní Novákovi, zavolali jsme Vás, protože se bojíme o Zuzanu. Víte, že Vaše dcera ____?', pick: 1 },
    { card_set_id: setId, text: 'Pokud nemůžeš být s tím, koho miluješ, miluj ____.', pick: 1 },
    { card_set_id: setId, text: 'Přináší Pilsner Urquell, oficiální pivo ____.', pick: 1 },
    { card_set_id: setId, text: 'Klikněte SEM pro ____.', pick: 1 },
    { card_set_id: setId, text: 'Koukej kámo, tomuhle tanečnímu pohybu říkám "____".', pick: 1 },
    { card_set_id: setId, text: 'Běží liška k Táboru, nese ____.', pick: 1 },
    { card_set_id: setId, text: 'Pánské obleky: zaručujeme, že se Vám bude líbit ____!', pick: 1 },
    { card_set_id: setId, text: 'Tady Epstein, chtěl bych si objednat ____ na svůj ostrov!', pick: 1 },
    { card_set_id: setId, text: 'Maminka vždycky říkala, že život je jako ____.', pick: 1 },
    { card_set_id: setId, text: 'Nový školní předmět: Úvod do ____.', pick: 1 },
    { card_set_id: setId, text: 'Na příští teambuilding si místo bowlingu zkusíme ____.', pick: 1 },
    { card_set_id: setId, text: 'Vítejte v budoucnosti. Místo práce vás čeká ____.', pick: 1 },
    { card_set_id: setId, text: 'Politici slibují, že do roku 2030 vyřeší ____.', pick: 1 },
    { card_set_id: setId, text: 'Když jsem otevřel ledničku, našel jsem tam ____.', pick: 1 },
    { card_set_id: setId, text: 'Doktor mi předepsal ____ třikrát denně.', pick: 1 },
    { card_set_id: setId, text: 'Když to nevyjde s kariérou, vždycky tu je ____.', pick: 1 },
    { card_set_id: setId, text: 'Můj startup vydělal miliony díky ____.', pick: 1 },
    { card_set_id: setId, text: 'První věc, kterou udělám po výplatě, je ____.', pick: 1 },
    { card_set_id: setId, text: 'Na maturitní otázku jsem odpověděl: ____.', pick: 1 },
    { card_set_id: setId, text: 'Ve skutečnosti za vším stojí ____.', pick: 1 },
    { card_set_id: setId, text: 'V návodu to bylo jasně napsané: Nepoužívejte ____.', pick: 1 },
    { card_set_id: setId, text: 'Tento týden v Praze lidé protestovali kvůli ____.', pick: 1 },
    { card_set_id: setId, text: 'Ministerstvo životního prostředí právě změnilo pravidla pro ____.', pick: 1 },
    { card_set_id: setId, text: 'Pražská kavárna dnes nabízí kávu s příchutí ____.', pick: 1 },
    { card_set_id: setId, text: 'V kavárně jsem potkal člověka, který nosil tričko s nápisem: ____.', pick: 1 },
    { card_set_id: setId, text: 'V Liberci se teď nejvíc řeší ____.', pick: 1 },
    { card_set_id: setId, text: 'Na afterparty s P. Diddym jsme všichni koukali na ____.', pick: 1 },
    { card_set_id: setId, text: 'Nová sezóna Stranger Things je o ____.', pick: 1 },
    { card_set_id: setId, text: 'Když jsem se na ig vydával za 13letou holku, narazil jsem na ____.', pick: 1 },
    { card_set_id: setId, text: '„Tohle nikdy nemělo opustit sklep,“ řekl a ukázal na ____.', pick: 1 },
    { card_set_id: setId, text: 'V uniklých e-mailech JE se mluvilo o ____.', pick: 1 },
    { card_set_id: setId, text: '____ je lepší než ____.', pick: 2 },
    { card_set_id: setId, text: '____ je vždycky horší, než ____.', pick: 2 }
  ]);

  await knex('white_cards').insert([
    { card_set_id: setId, text: 'Černý hajlující muž.' },
    { card_set_id: setId, text: 'Masturbace na různých místech kamarádova bytu.' },
    { card_set_id: setId, text: 'Vyhubení židovské rasy.' },
    { card_set_id: setId, text: 'Ljuba.' },
    { card_set_id: setId, text: 'Epsteinův ostrov.' },
    { card_set_id: setId, text: 'Masivní orální sex.' },
    { card_set_id: setId, text: 'Sklep plný dětí.' },
    { card_set_id: setId, text: 'Fanoušci Filipa Turka.' },
    { card_set_id: setId, text: 'Adolf Hitler.' },
    { card_set_id: setId, text: 'Naprosto neférová skinheadská bitka.' },
    { card_set_id: setId, text: 'Hajlování.' },
    { card_set_id: setId, text: 'Masivní prstění chlupaté kundičky.' },
    { card_set_id: setId, text: 'Když ji vylížeš a na jazyku ti zůstane chlup.' },
    { card_set_id: setId, text: 'Naolejovaný černý penis.' },
    { card_set_id: setId, text: 'Velký plyšový penis v dětském pokoji.' },
    { card_set_id: setId, text: 'Vyšukaná babička v koncentračním táboře.' },
    { card_set_id: setId, text: 'Rybníček - zastávka Reného Matouška a dalších libereckých signatářů Charty 77' },
    { card_set_id: setId, text: 'Skupina gayů.' },
    { card_set_id: setId, text: 'Partičky potloukající se kolem Fügnerky.' },
    { card_set_id: setId, text: 'Protržený kondom.' },
    { card_set_id: setId, text: 'Dětské porno zabavené při domovní prohlídce.' },
    { card_set_id: setId, text: 'Sex s nevlastní sestrou.' },
    { card_set_id: setId, text: 'Roztrhané trenky."' },
    { card_set_id: setId, text: 'Nevyčerpatelné zásoby dětského oleje.' },
    { card_set_id: setId, text: 'Sperma nastříkané do polévky.' },
    { card_set_id: setId, text: 'Kurvy, chlast a chlebíčky.' },
    { card_set_id: setId, text: 'Znásilněné holčičky.' },
    { card_set_id: setId, text: 'Ticho.' },
    { card_set_id: setId, text: 'Iluze svobodné volby v pozdně kapitalistické společnosti.' },
    { card_set_id: setId, text: 'Hladomor.' },
    { card_set_id: setId, text: 'Masožravé bakterie.' },
    { card_set_id: setId, text: 'Dlouhá plandající péra.' },
    { card_set_id: setId, text: 'Totální nezájem o problémy Třetího světa.' },
    { card_set_id: setId, text: 'Špatný pokus o roli otce.' },
    { card_set_id: setId, text: 'Vidět co se stane, pokud zamknete lidi v pokoji s hladovými holuby.' },
    { card_set_id: setId, text: 'Ukřižování.' },
    { card_set_id: setId, text: 'Práskač.' },
    { card_set_id: setId, text: '72 panen.' },
    { card_set_id: setId, text: 'Paradox cestování časem.' },
    { card_set_id: setId, text: 'Pravá německá kuchyně.' },
    { card_set_id: setId, text: 'Páchání trestných činů.' },
    { card_set_id: setId, text: 'COVID-19.' },
    { card_set_id: setId, text: 'Zničující dluh.' },
    { card_set_id: setId, text: 'Použité kalhotky.' },
    { card_set_id: setId, text: 'Prdnutí tak veliké, že by vzbudilo obry z tisíceletého spánku.' },
    { card_set_id: setId, text: 'Bývalý prezident George W. Bush.' },
    { card_set_id: setId, text: 'Kompletní nahota zepředu.' },
    { card_set_id: setId, text: 'Posypat se parmazánem a chilli, protože jsem Pizza!' },
    { card_set_id: setId, text: 'Nahý se dívat na Studio Kamarád.' },
    { card_set_id: setId, text: 'Předstírat zájem.' },
    { card_set_id: setId, text: 'Mít velké sny a žádnou realistickou cestu, jak jich dosáhnout.' },
    { card_set_id: setId, text: 'Vidět babičku nahou.' },
    { card_set_id: setId, text: 'Šušně.' },
    { card_set_id: setId, text: 'Nevyhnutelné vyhasnutí Vesmíru.' },
    { card_set_id: setId, text: 'Zázrak početí.' },
    { card_set_id: setId, text: 'Nanebevstoupení.' },
    { card_set_id: setId, text: 'Mít infarkt.' },
    { card_set_id: setId, text: 'Privilegia bílých.' },
    { card_set_id: setId, text: 'Vynořivší se z moře a demolující Tokyo.' },
    { card_set_id: setId, text: 'Lupič hamburgerů.' },
    { card_set_id: setId, text: 'AXE tělový deodorant.' },
    { card_set_id: setId, text: 'Kristova krev.' },
    { card_set_id: setId, text: 'Dělat to do zadku.' }, 
    { card_set_id: setId, text: 'Má bývalá žena.' },
    { card_set_id: setId, text: 'Učit robota lásce.' },
    { card_set_id: setId, text: 'Šáhnout mopslíkovi na penis.' },
    { card_set_id: setId, text: 'Mlýn plný těl.' },
    { card_set_id: setId, text: 'Nesquik.' },
    { card_set_id: setId, text: 'Vladimir Putin.' },
    { card_set_id: setId, text: 'Patriarchát.' },
    { card_set_id: setId, text: 'Skleněný strop.' },
    { card_set_id: setId, text: 'Zvracet mořské plody a krvácet z análu.' },
    { card_set_id: setId, text: 'Americký sen.' },
    { card_set_id: setId, text: 'Chodit naostro.' },
    { card_set_id: setId, text: 'Nakadit do notebooku a pak ho zaklapnout.' },
    { card_set_id: setId, text: 'Mrtvé děti.' },
    { card_set_id: setId, text: 'Předkožka.' },
    { card_set_id: setId, text: 'Sólo na saxofon.' },
    { card_set_id: setId, text: 'Italové.' },
    { card_set_id: setId, text: 'Plod.' },
    { card_set_id: setId, text: 'Vystřelit do vzduchu, když až po koule vězíš v kvičícím divočákovi.' },
    { card_set_id: setId, text: 'Nežný misionářský sex s polibky.' },
    { card_set_id: setId, text: 'BATMAN!' },
    { card_set_id: setId, text: 'Zemědělství.' },
    { card_set_id: setId, text: 'Dělat za 149,- Kč/h.' },
    { card_set_id: setId, text: 'Přírodní výběr.' },
    { card_set_id: setId, text: 'Potraty ramínkem na šaty.' },
    { card_set_id: setId, text: 'Sex s Filipem Turkem.' },
    { card_set_id: setId, text: 'Můj násilnický přítel, který není tak zlý, když ho poznáte.' },
    { card_set_id: setId, text: 'Analgetika na předpis.' },
    { card_set_id: setId, text: 'Kadit při plavání.' },
    { card_set_id: setId, text: 'Homosexuálně laděný volejbalový sestřih.' },
    { card_set_id: setId, text: 'Dát věci tam, kam patří.' },
    { card_set_id: setId, text: 'Křehká mužnost.' },
    { card_set_id: setId, text: 'Sněz-kolik-zvládneš krevet za stovku.' },
    { card_set_id: setId, text: 'Téměř mrtvý stařík.' },
    { card_set_id: setId, text: 'Rytmus.' },
    { card_set_id: setId, text: 'Roztavený sýr.' },
    { card_set_id: setId, text: 'Velociraptoři útoky.' },
    { card_set_id: setId, text: '7 mrtvých a 3 v kritickém stavu.' },
    { card_set_id: setId, text: 'Hlen.' },
    { card_set_id: setId, text: 'Alkoholismus.' },
    { card_set_id: setId, text: 'Dospělý muž na kolečkových bruslích.' },
    { card_set_id: setId, text: 'Chytit svého muže za madla lásky a ojet jeho velkou prdel.' },
    { card_set_id: setId, text: 'Přerostlé lízátko.' },
    { card_set_id: setId, text: 'Sebenenávist.' },
    { card_set_id: setId, text: 'Ujetá předehra.' },
    { card_set_id: setId, text: 'Písmo Svaté.' },
    { card_set_id: setId, text: 'Německé sklepní porno.' },
    { card_set_id: setId, text: 'Hořet.' },
    { card_set_id: setId, text: 'Těhotenství náctiletých.' },
    { card_set_id: setId, text: 'Tvůj divný bratr.' },
    { card_set_id: setId, text: 'Masturbátor Ušatá Bára®.' },
    { card_set_id: setId, text: 'Pyramida z lebek.' },
    { card_set_id: setId, text: 'Erekce co vydrží přes 4 hodiny.' },
    { card_set_id: setId, text: 'Trojka s mojí ženou a Brucem Willisem.' },
    { card_set_id: setId, text: 'Minulost.' },
    { card_set_id: setId, text: 'Mé genitálie.' },
    { card_set_id: setId, text: 'Nekonečný průjem.' },
    { card_set_id: setId, text: 'Věda.' },
    { card_set_id: setId, text: 'Neopětovaný orální sex.' },
    { card_set_id: setId, text: 'Nelétaví ptáci.' },
    { card_set_id: setId, text: 'Pořádné šupnutí.' },
    { card_set_id: setId, text: '50 000 voltů přímo do bradavek.' },
    { card_set_id: setId, text: 'Vyvážená snídaně.' },
    { card_set_id: setId, text: 'Všude mrtví ptáci.' },
    { card_set_id: setId, text: 'Anální výplach.' },
    { card_set_id: setId, text: 'Jezení sušeného masa.' },
    { card_set_id: setId, text: 'Vynález pizzy.' },
    { card_set_id: setId, text: 'Syndrom orgasmické tváře.' },
    { card_set_id: setId, text: 'Studená, osvěžující chuť Pepsi®.' },
    { card_set_id: setId, text: 'Chemické zbraně.' },
    { card_set_id: setId, text: 'Helena Růžičková.' },
    { card_set_id: setId, text: 'Říkat si, jestli by si šlo vzít trochu chilli omáčky sebou.' },
    { card_set_id: setId, text: 'Banány.' },
    { card_set_id: setId, text: 'Pasivně agresivní Post-it lístečky.' },
    { card_set_id: setId, text: 'Mailová schránka Jefreyho Epsteina.' },
    { card_set_id: setId, text: 'Přejít k AAA Direct pojišťovně.' },
    { card_set_id: setId, text: 'Trošku si učůrnout.' },
    { card_set_id: setId, text: 'Vlhké sny.' },
    { card_set_id: setId, text: 'Židé.' },
    { card_set_id: setId, text: 'Manžel zkurvysyn, podvodník.' },
    { card_set_id: setId, text: 'Silná stehna.' },
    { card_set_id: setId, text: 'Tyto děvky.' },
    { card_set_id: setId, text: 'Jediný gay v okruhu 100km.' },
    { card_set_id: setId, text: 'První milování v životě.' },
    { card_set_id: setId, text: 'Donald Trump.' },
    { card_set_id: setId, text: 'Políbit babičku na čelo a odpojit ji od přístrojů.' },
    { card_set_id: setId, text: 'Sexuální tenze.' },
    { card_set_id: setId, text: 'Útočná puška M4A1.' },
    { card_set_id: setId, text: 'Kulkou přímo do řiti.' },
    { card_set_id: setId, text: 'Má nejlepší podprsenka.' },
    { card_set_id: setId, text: 'Praštit senátora do ksichtu.' },
    { card_set_id: setId, text: 'Být boháč.' },
    { card_set_id: setId, text: 'Přesladká pomsta.' },
    { card_set_id: setId, text: 'Republikáni.' },
    { card_set_id: setId, text: 'Přivonět a zlíbat nohy.' },
    { card_set_id: setId, text: 'O mnoho mladší žena.' },
    { card_set_id: setId, text: 'Chudoba.' },
    { card_set_id: setId, text: 'Piloti kamikaze.' },
    { card_set_id: setId, text: 'Spáchat sebevraždu.' },
    { card_set_id: setId, text: 'Homosexuální agenda.' },
    { card_set_id: setId, text: 'Cikán.' },
    { card_set_id: setId, text: 'Sokol s čepičkou.' },
    { card_set_id: setId, text: 'Kouzelná hudba.' },
    { card_set_id: setId, text: 'Alzák.' },
    { card_set_id: setId, text: 'Vysvětlovat rozdíl mezi pohlavím a genderem.' },
    { card_set_id: setId, text: 'Vzorky zdarma.' },
    { card_set_id: setId, text: 'Ublížit těm nejbližším.' },
    { card_set_id: setId, text: 'Dělat správnou věc.' },
    { card_set_id: setId, text: 'Nevýhodný kompromis.' },
    { card_set_id: setId, text: 'Světový mír.' },
    { card_set_id: setId, text: 'Sklapnout abych mohl sledovat fotbal.' },
    { card_set_id: setId, text: 'Jíst vajíčko natvrdo z manželovy řitě.' },
    { card_set_id: setId, text: 'RoboCop.' },
    { card_set_id: setId, text: 'Jedna koza venku.' },
    { card_set_id: setId, text: 'Justit Bieber.' },
    { card_set_id: setId, text: 'Umpalumpové.' },
    { card_set_id: setId, text: 'Nevhodné jódlování.' },
    { card_set_id: setId, text: 'Puberta.' },
    { card_set_id: setId, text: 'Duchové.' },
    { card_set_id: setId, text: 'Krabička Neurolu denně.' },
    { card_set_id: setId, text: 'Jebat svou sestru.' },
    { card_set_id: setId, text: 'Uplést cop ze 3 penisů.' },
    { card_set_id: setId, text: 'Energické jazzové ruce.' },
    { card_set_id: setId, text: 'Být prstěn.' },
    { card_set_id: setId, text: 'Můj řidič Uberu.' },
    { card_set_id: setId, text: 'Jogobella.' },
    { card_set_id: setId, text: 'Policejní brutalita.' },
    { card_set_id: setId, text: 'Plnit kufřík pracovními věcmi.' },
    { card_set_id: setId, text: 'Předpubertální děti.' },
    { card_set_id: setId, text: 'Má tlustá dcera.' },
    { card_set_id: setId, text: 'Rapová hudba.' },
    { card_set_id: setId, text: 'Vytratit se ze světa.' },
    { card_set_id: setId, text: 'Darth Vader.' },
    { card_set_id: setId, text: 'Smutné vyhonění.' },
    { card_set_id: setId, text: 'Přesně to, co jsi čekal.' },
    { card_set_id: setId, text: 'Čekat krknutí a pak se poblít.' },
    { card_set_id: setId, text: 'Tvoje matka.' },
    { card_set_id: setId, text: 'Prso zboku.' },
    { card_set_id: setId, text: 'Chobotnice honící 7 penisů a kouřící cigaretu.' },
    { card_set_id: setId, text: 'Aft.' },
    { card_set_id: setId, text: 'Vorvaň.' },
    { card_set_id: setId, text: 'Etnické ženy.' },
    { card_set_id: setId, text: 'Muži probírající svoje pocity zdravým způsobem.' },
    { card_set_id: setId, text: 'Incest.' },
    { card_set_id: setId, text: 'PacMan nekontrolovaně požírající semeno.' },
    { card_set_id: setId, text: 'Nenuceně navržená trojka.' },
    { card_set_id: setId, text: 'Docházející sperma.' },
    { card_set_id: setId, text: 'Bůh.' },
    { card_set_id: setId, text: 'Přejet Tatrou přes dítě.' },
    { card_set_id: setId, text: 'Močení do mé žíznivé pusy.' },
    { card_set_id: setId, text: 'Emoce.' },
    { card_set_id: setId, text: 'Olizovat věci, aby byly moje.' },
    { card_set_id: setId, text: 'Práce.' },
    { card_set_id: setId, text: 'Placenta.' },
    { card_set_id: setId, text: 'Samovznícení člověka.' },
    { card_set_id: setId, text: 'Finále Farmář hledá ženu.' },
    { card_set_id: setId, text: 'Házet po člověku pomeranče, až se z toho zcvokne.' },
    { card_set_id: setId, text: 'Získat nadvládu.' },
    { card_set_id: setId, text: 'Smard týden nemitého penisu.' },
    { card_set_id: setId, text: 'Malování prsty.' },
    { card_set_id: setId, text: 'Pach starých lidí.' },
    { card_set_id: setId, text: 'Moji vnitřní démoni.' },
    { card_set_id: setId, text: 'Vodní pistole plná chcanek.' },
    { card_set_id: setId, text: 'Milan Rastislav Štefánik.' },
    { card_set_id: setId, text: 'Tulení se.' },
    { card_set_id: setId, text: 'Tráva za 500.' },
    { card_set_id: setId, text: 'Amputace v bitevních podmínkách.' },
    { card_set_id: setId, text: 'Špagety? Zase??' },
    { card_set_id: setId, text: 'Nevydařená narozeninová oslava.' },
    { card_set_id: setId, text: 'Nachos pro tento stůl.' },
    { card_set_id: setId, text: 'Nespolupracující spoluhráč.' },
    { card_set_id: setId, text: 'Malinkatý koník.' },
    { card_set_id: setId, text: 'Krab.' },
    { card_set_id: setId, text: 'Prodávat kokain dětem.' },
    { card_set_id: setId, text: 'Tmavočeši.' },
    { card_set_id: setId, text: 'Vzájemná destrukce zaručena.' },
    { card_set_id: setId, text: 'Pedofilové.' },
    { card_set_id: setId, text: 'Droždí.' },
    { card_set_id: setId, text: 'Jak hrozně moje dcera posrala svoje taneční vystoupení.' },
    { card_set_id: setId, text: 'Čtverce.' },
    { card_set_id: setId, text: 'Katapulty.' },
    { card_set_id: setId, text: 'Chudí lidé.' },
    { card_set_id: setId, text: 'Chodit pouze s asiatkami.' },
    { card_set_id: setId, text: 'Síla.' },
    { card_set_id: setId, text: 'Jak úžasné je sjet se houbičkami.' },
    { card_set_id: setId, text: 'Každého soudit.' },
    { card_set_id: setId, text: 'Vzít se, mít pár dětí, koupit nějaké věci, na důchod se odstěhovat na Floridu a umřít.' },
    { card_set_id: setId, text: 'Proklatě ticho a klid.' },
    { card_set_id: setId, text: 'AIDS.' },
    { card_set_id: setId, text: 'Obrázky prsou.' },
    { card_set_id: setId, text: 'Silné ženské hrdinky.' },
    { card_set_id: setId, text: 'Hospicová péče.' },
    { card_set_id: setId, text: 'Fakt se sjet.' },
    { card_set_id: setId, text: 'Léčba homosexuality.' },
    { card_set_id: setId, text: 'Burgery a píča.' },
    { card_set_id: setId, text: 'Ku-klux-klan.' },
    { card_set_id: setId, text: 'Sexuálně nevyhraněná chobotnice, která hledá ve vesmíru lásku.' },
    { card_set_id: setId, text: 'Heroin.' },
    { card_set_id: setId, text: 'Nevolnictví.' },
    { card_set_id: setId, text: 'Přidržet dítě a poprdět ho.' },
    { card_set_id: setId, text: 'Jojo.' },
    { card_set_id: setId, text: 'Být stále pannou/panicem.' },
    { card_set_id: setId, text: 'Řešit problémy násilím.' },
    { card_set_id: setId, text: 'Být postříkán/a.' },
    { card_set_id: setId, text: 'Rozpixelované bukake.' },
    { card_set_id: setId, text: 'Celoživotní smutek.' },
    { card_set_id: setId, text: 'Celý den bez masturbace.' },
    { card_set_id: setId, text: 'Zanedbávat partnera kvůli hraní Brawl Stars.' },
    { card_set_id: setId, text: 'Společné sledování seriálů na Netflixu.' },
    { card_set_id: setId, text: 'Dickobrazy.' },
    { card_set_id: setId, text: 'Rasismus.' },
    { card_set_id: setId, text: 'Vzteklý PMS.' },
    { card_set_id: setId, text: 'Sluníčko a duha.' },
    { card_set_id: setId, text: 'Radikální islámský terorismus.' },
    { card_set_id: setId, text: 'Mohutné bicepsy.' },
    { card_set_id: setId, text: 'Moje malá erekce.' },
    { card_set_id: setId, text: 'Nabírat na zvracení.' },
    { card_set_id: setId, text: 'Ranní výstřik v paprscích vycházejícího slunce.' },
    { card_set_id: setId, text: 'Popravit rukojmí každou hodinu.' },
    { card_set_id: setId, text: 'Africké rytmy.' },
    { card_set_id: setId, text: 'Propuknout ve zpěv a tanec.' },
    { card_set_id: setId, text: 'Lepra.' },
    { card_set_id: setId, text: 'Gloryholes.' },
    { card_set_id: setId, text: 'Ztopořené bradavky.' },
    { card_set_id: setId, text: 'Srdce dítěte.' },
    { card_set_id: setId, text: 'Štěňátka!' },
    { card_set_id: setId, text: 'Bratrstvo Ježíšovo.' },
    { card_set_id: setId, text: 'Klučičí penisy.' },
    { card_set_id: setId, text: 'Probudit se nahý na parkovišti u Lidlu.' },
    { card_set_id: setId, text: 'Starší žena, která to s penisem umí.' },
    { card_set_id: setId, text: 'Dostat drogy z ulice a do mého těla.' },
    { card_set_id: setId, text: 'Sladká prdelka Vojty Kotka.' },
    { card_set_id: setId, text: 'Aktivní naslouchání.' },
    { card_set_id: setId, text: 'Etnické čistky.' },
    { card_set_id: setId, text: 'Svědící frnda.' },
    { card_set_id: setId, text: 'Vykouřit příteli tak tvrdě, že by se posral.' },
    { card_set_id: setId, text: 'Vagón mandlí.' },
    { card_set_id: setId, text: 'Čekat na sex do svatby.' },
    { card_set_id: setId, text: 'Nepředstavitelná blbost.' },
    { card_set_id: setId, text: 'Blýskavé věcičky.' },
    { card_set_id: setId, text: 'Ďábel sám.' },
    { card_set_id: setId, text: 'Sebekanibalismus.' },
    { card_set_id: setId, text: 'Porucha erekce.' },
    { card_set_id: setId, text: 'Má kolekce japonských sexuálních hraček.' },
    { card_set_id: setId, text: 'Papež.' },
    { card_set_id: setId, text: 'Běloši.' },
    { card_set_id: setId, text: 'Má, světle růžová, dírka na mrdání.' },
    { card_set_id: setId, text: 'Jak daleko dostanu penis do vlastní řitě.' },
    { card_set_id: setId, text: 'Mít řitě místo očí.' },
    { card_set_id: setId, text: 'Sólo na píšťalku písně „My Heart Will Go On“.' },
    { card_set_id: setId, text: 'Kouzlo živého divadla.' },
    { card_set_id: setId, text: 'Hodit pannu do kráteru sopky.' },
    { card_set_id: setId, text: 'Přijmout věci tak, jak jsou.' },
    { card_set_id: setId, text: 'Terapie.' },
    { card_set_id: setId, text: 'Být hloupý a tlustý.' },
    { card_set_id: setId, text: 'Kadit tam a zpět. Navždy.' },
    { card_set_id: setId, text: 'Natrhnout prdel tak snadno, jako balící papír na Vánoce.' },
    { card_set_id: setId, text: 'Víc slonního penisu, než jsem chtěl.' },
    { card_set_id: setId, text: 'Slané překvapení.' },
    { card_set_id: setId, text: 'Jih.' },
    { card_set_id: setId, text: 'Porušení našich základních lidských práv.' },
    { card_set_id: setId, text: 'Tančit step jako by nebylo zítřka.' },
    { card_set_id: setId, text: 'Konsenzuální sex.' },
    { card_set_id: setId, text: 'Vyprávět mizernou historku, která nemá konec.' },
    { card_set_id: setId, text: 'Dobrá silná gorila.' },
    { card_set_id: setId, text: 'Vidět svého otce plakat.' },
    { card_set_id: setId, text: 'Nekrofilie.' },
    { card_set_id: setId, text: 'Být ženou.' },
    { card_set_id: setId, text: 'Dostat se do vážné autohavárie.' },
    { card_set_id: setId, text: 'Černoši.' },
    { card_set_id: setId, text: 'Jídelní krabičky.' },
    { card_set_id: setId, text: 'Kurvy.' },
    { card_set_id: setId, text: 'Ten pankáč, co mi ukradl svačinu.' },
    { card_set_id: setId, text: 'Sirotci nad kterými se srdce slituje.' },
    { card_set_id: setId, text: 'Prdelatí chlapci.' },
    { card_set_id: setId, text: 'Mísa tatarky a lidských zubů.' },
    { card_set_id: setId, text: 'Pálivá hovínka.' },
    { card_set_id: setId, text: 'Říct „Miluji Tě“.' },
    { card_set_id: setId, text: 'Nacpat si velkou zavařovačku do řitě.' },
    { card_set_id: setId, text: 'Pravý smysl Vánoc.' },
    { card_set_id: setId, text: 'Někteří z nejlepších rapperů v oboru.' },
    { card_set_id: setId, text: 'Vlastnit a provozovat restauraci McDonalds.' },
    { card_set_id: setId, text: 'Estrogen.' },
    { card_set_id: setId, text: 'Holky.' },
    { card_set_id: setId, text: 'Rusové.' },
    { card_set_id: setId, text: 'Vybělená řiť.' },
    { card_set_id: setId, text: 'Temné a tajuplné síly mimo naši kontrolu.' },
    { card_set_id: setId, text: 'Pokrývka od neštovic.' },
    { card_set_id: setId, text: 'Masturbovat.' },
    { card_set_id: setId, text: 'Tuláci.' },
    { card_set_id: setId, text: 'Prdět vagínou.' },
    { card_set_id: setId, text: 'Poradci z Jak se staví sen.' },
    { card_set_id: setId, text: 'Viagra.' },
    { card_set_id: setId, text: 'Příliš horká polévka.' },
    { card_set_id: setId, text: 'Mohamed. Nechť je mír při něm.' },
    { card_set_id: setId, text: 'Vysvětlovat jak funguje vagína.' },
    { card_set_id: setId, text: 'Lucie Bílá.' },
    { card_set_id: setId, text: 'Pít o samotě.' },
    { card_set_id: setId, text: 'Nešika.' },
    { card_set_id: setId, text: 'Několik bodných ran.' },
    { card_set_id: setId, text: 'Pokaděné pleny.' },
    { card_set_id: setId, text: 'Podporující dotyk na bedrech.' },
    { card_set_id: setId, text: 'Anální kuličky.' },
    { card_set_id: setId, text: 'Zmasakrovat nevinné civilisty.' },
    { card_set_id: setId, text: 'Stáhnout se.' },
    { card_set_id: setId, text: 'Rozumět řeči slonů.' },
    { card_set_id: setId, text: 'Koňské maso.' },
    { card_set_id: setId, text: 'Opravdu pěkný klobouk.' },
    { card_set_id: setId, text: 'Stalin.' },
    { card_set_id: setId, text: 'Ztracený puberťák.' },
    { card_set_id: setId, text: 'Uctívat tuto kundičku.' },
    { card_set_id: setId, text: 'Zcela neoprávněná důvěra.' },
    { card_set_id: setId, text: 'Účastníci dětské Miss krásy.' },
    { card_set_id: setId, text: 'Výbuchy.' },
    { card_set_id: setId, text: 'Neočkovat své děti, protože jsem debil.' },
    { card_set_id: setId, text: 'Náš vibrátor.' },
    { card_set_id: setId, text: 'Čuchat barvy.' },
    { card_set_id: setId, text: 'Muž napokraji orgasmu.' },
    { card_set_id: setId, text: 'Represe.' },
    { card_set_id: setId, text: 'Obsazení Polska.' },
    { card_set_id: setId, text: 'Moje vagína.' },
    { card_set_id: setId, text: 'Bezprdelní týpci.' },
    { card_set_id: setId, text: 'Vražda.' },
    { card_set_id: setId, text: 'Dát tomu 110 %.' },
    { card_set_id: setId, text: 'Její výsost, královna Alžběta II.' },
    { card_set_id: setId, text: 'Černý Ježíš.' },
    { card_set_id: setId, text: 'Memy.' },
    { card_set_id: setId, text: '67 meme.' },
    { card_set_id: setId, text: 'Sex se zvířaty.' },
    { card_set_id: setId, text: 'Být utiskován.' },
    { card_set_id: setId, text: 'Goblini.' },
    { card_set_id: setId, text: 'Naděje.' },
    { card_set_id: setId, text: 'Andrej Babiš.' },
    { card_set_id: setId, text: '10,000 syrských uprchlíků.' },
    { card_set_id: setId, text: 'Vynucená sterilizace.' },
    { card_set_id: setId, text: 'Rodinný stav.' },
    { card_set_id: setId, text: 'Nechtěné těhotenství.' },
    { card_set_id: setId, text: 'Zázrak.' },
    { card_set_id: setId, text: 'Můj šéf.' },
    { card_set_id: setId, text: 'Včely?' },
    { card_set_id: setId, text: 'Harry Potter erotika.' },
    { card_set_id: setId, text: 'Porodit Antikrista.' },
    { card_set_id: setId, text: 'Tři čůráci najednou.' },
    { card_set_id: setId, text: 'Náckové.' },
    { card_set_id: setId, text: 'Dvacet deka skvělého mexického surového heroinu.' },
    { card_set_id: setId, text: 'To, co ta pusa dělá.' },
    { card_set_id: setId, text: 'Mrtví rodiče.' },
    { card_set_id: setId, text: 'Stálost objektu.' },
    { card_set_id: setId, text: 'Rasistické otázky ve Scio testu.' },
    { card_set_id: setId, text: 'Velká hospodářská krize.' },
    { card_set_id: setId, text: 'Motorové pily místo rukou.' },
    { card_set_id: setId, text: 'Liberálové.' },
    { card_set_id: setId, text: 'Mikropenis.' },
    { card_set_id: setId, text: 'Má duše.' },
    { card_set_id: setId, text: 'Kulička z ušního mazu, semene a ostřižků nehtů.' },
    { card_set_id: setId, text: 'Vikingská horda.' },
    { card_set_id: setId, text: 'Teplí lidé.' },
    { card_set_id: setId, text: 'Dusit v sobě nespravedlnost.' },
    { card_set_id: setId, text: 'Oidipův komplex.' },
    { card_set_id: setId, text: 'Husy.' },
    { card_set_id: setId, text: 'Extrémně těsné kalhoty.' },
    { card_set_id: setId, text: 'TV Prima.' },
    { card_set_id: setId, text: 'Malý chlapec, který doprdele nasklapne o dinosaurech.' },
    { card_set_id: setId, text: 'Udělat trucující obličej.' },
    { card_set_id: setId, text: 'Zabití motorovým vozidlem.' },
    { card_set_id: setId, text: 'Volební práva žen.' },
    { card_set_id: setId, text: 'Nějaký týpek.' },
    { card_set_id: setId, text: 'Soudce Barbara.' },
    { card_set_id: setId, text: 'Ilegální přistěhovalci.' },
    { card_set_id: setId, text: 'Postarší japonští muži.' },
    { card_set_id: setId, text: 'Ženský orgasmus.' },
    { card_set_id: setId, text: 'Heteronormativita.' },
    { card_set_id: setId, text: 'Drobky po celém zatraceném koberci.' },
    { card_set_id: setId, text: 'Arnold Swarzeneger.' },
    { card_set_id: setId, text: 'Heslo na wifi.' },
    { card_set_id: setId, text: 'Úchvatné bicáky.' },
    { card_set_id: setId, text: 'Pták co sere lidská hovna.' },
    { card_set_id: setId, text: 'Smutný lev ze ZOO.' },
    { card_set_id: setId, text: 'Pytlík magických fazolí.' },
    { card_set_id: setId, text: 'Špatné životní volby.' },
    { card_set_id: setId, text: 'Můj sexuální život.' },
    { card_set_id: setId, text: 'Koncentrační tábor Osvětim.' },
    { card_set_id: setId, text: 'Kajmanka zakousnutá do špičky tvého penisu.' },
    { card_set_id: setId, text: 'Všichni chlapi, které jsem ojela.' },
    { card_set_id: setId, text: 'Klitoris.' },
    { card_set_id: setId, text: 'Velký třesk.' },
    { card_set_id: setId, text: 'Nášlapná mina.' },
    { card_set_id: setId, text: 'Malé prasátko s pláštěnkou a botičkami.' },
    { card_set_id: setId, text: 'Smrdutý penis.' },
    { card_set_id: setId, text: 'Vyhonit si do moře dětských slz.' },
    { card_set_id: setId, text: 'Skočit pod jedoucí metro.' },
    { card_set_id: setId, text: 'Když zjistíš, že ti už došli děti ve sklepě.' },
    { card_set_id: setId, text: 'Neplánované početí.' },
    { card_set_id: setId, text: 'Nucený potrat.' },
    { card_set_id: setId, text: 'Ukamenování nevinného.' },
    { card_set_id: setId, text: 'Lidské maso.' },
    { card_set_id: setId, text: 'Čas pro sebe.' },
    { card_set_id: setId, text: 'Podzemní železnice.' },
    { card_set_id: setId, text: 'Moře problémů.' },
    { card_set_id: setId, text: 'Fantazie o dřevorubcích.' },
    { card_set_id: setId, text: 'Hlas Morgana Freemena.' },
    { card_set_id: setId, text: 'Prostata.' },
    { card_set_id: setId, text: 'Být kurevský čaroděj.' },
    { card_set_id: setId, text: 'Moje černá prdel.' },
    { card_set_id: setId, text: 'Pravý lidský kontakt.' },
    { card_set_id: setId, text: 'Oznámit, že už budu.' },
    { card_set_id: setId, text: 'Koule.' },
    { card_set_id: setId, text: 'Babička.' },
    { card_set_id: setId, text: 'Tření.' },
    { card_set_id: setId, text: 'Kousky mrtvého stopaře.' },
    { card_set_id: setId, text: 'Prdnout si a vzdálit se.' },
    { card_set_id: setId, text: 'Být za kreténa vůči dětem.' },
    { card_set_id: setId, text: 'Jeden trilion dolarů.' },
    { card_set_id: setId, text: 'Utopit děti ve vaně.' },
    { card_set_id: setId, text: 'Umírání.' },
    { card_set_id: setId, text: 'Pít ze záchoda a jíst odpadky.' },
    { card_set_id: setId, text: 'Gayové.' },
    { card_set_id: setId, text: 'Výkřiky... strašlivé výkřiky.' },
    { card_set_id: setId, text: 'Muži.' },
    { card_set_id: setId, text: 'Vybombardování města Nagasaki.' },
    { card_set_id: setId, text: 'Falešná prsa.' },
    { card_set_id: setId, text: 'Má ošklivá tvář a špatná povaha.' },
    { card_set_id: setId, text: 'Kurevská nakládačka.' },
    { card_set_id: setId, text: 'Nádor na mozku.' },
    { card_set_id: setId, text: 'Strach sám.' },
    { card_set_id: setId, text: 'Židé, cikaní a homosexuálové.' },
    { card_set_id: setId, text: 'Mlíkař.' },
    { card_set_id: setId, text: 'Karty proti lidskosti.' },
  ]);

}