import { config as loadEnv } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';
import knexLib from 'knex';

loadEnv({ path: resolve(dirname(fileURLToPath(import.meta.url)), '../../../.env') });

const knex = knexLib({
  client: 'mysql2',
  connection: {
    host: process.env.DB_HOST ?? 'localhost',
    port: Number(process.env.DB_PORT ?? 3306),
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
  },
});

async function main() {
  const cardSets = await knex('card_sets').select('id', 'name', 'description', 'is_public', 'slug');
  const blackCards = await knex('black_cards').select('id', 'text', 'pick').orderBy('id');
  const whiteCards = await knex('white_cards').select('id', 'text').orderBy('id');
  const blackTrans = await knex('black_card_translations').select('black_card_id', 'language_code', 'text');
  const whiteTrans = await knex('white_card_translations').select('white_card_id', 'language_code', 'text');
  const blackAssign = await knex('card_set_black_cards').select('card_set_id', 'black_card_id');
  const whiteAssign = await knex('card_set_white_cards').select('card_set_id', 'white_card_id');

  await knex.destroy();

  const out = `import type { Knex } from 'knex';

// Auto-generated by scripts/generate-seeds.ts
// DO NOT EDIT MANUALLY

export async function seed(knex: Knex): Promise<void> {
  await knex.raw('SET FOREIGN_KEY_CHECKS=0');
  await knex('card_set_black_cards').truncate();
  await knex('card_set_white_cards').truncate();
  await knex('black_card_translations').truncate();
  await knex('white_card_translations').truncate();
  await knex('black_cards').truncate();
  await knex('white_cards').truncate();
  await knex('card_sets').truncate();
  await knex.raw('SET FOREIGN_KEY_CHECKS=1');

  await knex('card_sets').insert(${JSON.stringify(cardSets, null, 4)});

  await knex('black_cards').insert(${JSON.stringify(blackCards.map(({ id, text, pick }) => ({ id, text, pick })), null, 4)});

  await knex('white_cards').insert(${JSON.stringify(whiteCards.map(({ id, text }) => ({ id, text })), null, 4)});
${blackTrans.length > 0 ? `
  await knex('black_card_translations').insert(${JSON.stringify(blackTrans, null, 4)});` : ''}
${whiteTrans.length > 0 ? `
  await knex('white_card_translations').insert(${JSON.stringify(whiteTrans, null, 4)});` : ''}

  await knex('card_set_black_cards').insert(${JSON.stringify(blackAssign, null, 4)});

  await knex('card_set_white_cards').insert(${JSON.stringify(whiteAssign, null, 4)});
}
`;

  const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '../src/db/seeds/01_all_cards.ts');
  writeFileSync(outPath, out, 'utf-8');
  console.log(`Seed written to ${outPath}`);
  console.log(`  card_sets: ${cardSets.length}`);
  console.log(`  black_cards: ${blackCards.length} (deduplicated)`);
  console.log(`  white_cards: ${whiteCards.length} (deduplicated)`);
  console.log(`  black assignments: ${blackAssign.length}`);
  console.log(`  white assignments: ${whiteAssign.length}`);
}

main().catch(console.error);
